server:
  port: 8083

spring:
  application:
    name: policy-service
  datasource:
    url: jdbc:postgresql://localhost:5433/policy_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    com.insureflow: DEBUG
